language: python
python:
  - 2.6
  - 2.7
  - 3.3
# command to install dependencies
install:
  - pip install .
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
before_script:
  - pip install pytest-cov
script: py.test --cov pytoxml --cov-report term-missing
after_success:
  - coveralls
